name: RSS News Aggregator

on:
  #push
  schedule:
    - cron: '0 * * * *' # At the top of every hour
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # Updated to v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Updated to 3.11

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python feeds.py feeds.yaml temp.db > feeds.md

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          commit_prefix: "[AUTO-UPDATE]"
          commit_message: "RSS feeds updated - $(date '+%Y-%m-%d %H:%M:%S UTC')"
